name: Bot Extractor M3U8

on:
  schedule:
    - cron: '0 */6 * * *' # S'executa automàticament cada 6 hores (podes variar-ho si vols)
  workflow_dispatch:     # Afegeix el botó manual "Run workflow" a la web de GitHub

# Garantir per codi que el bot pugui escriure l'arxiu i fer el git push sense error 128
permissions:
  contents: write

jobs:
  extreure-enllac:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarregar el codi font actual del repositori
    - name: Baixar codi del repositori
      uses: actions/checkout@v4

    # 2. Configurar la versió de Python al servidor de GitHub
    - name: Configurar l'entorn de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Instal·lar l'última versió de Google Chrome al servidor virtual Linux
    - name: Instal·lar Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    # 4. Instal·lar Selenium de manera neta des de l'arxiu de requeriments
    - name: Instal·lar llibreries des de requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Executar el bot per obrir Chrome, interceptar el trànsit i escriure l'enllaç .m3u
    - name: Executar el bot de Python
      run: python bot_m3u8.py

    # 6. Desat automàtic de l'arxiu url.m3u a la branca del teu repositori
    - name: Guardar arxiu url.m3u al repositori
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add url.m3u
        git commit -m "Actualització automàtica del canal LleidaTV" || exit 0
        git push
